### ISSUE TITLE
Captcha position

### ISSUE THREAD

**Issue by Heggi95** [IT-PM-OpenAdaptronik/Webapp#103]
Beim Registrieren wird im Captcha Feld zusätzlich noch der Schrifttext "Captcha" angezeigt. Dieser überlappt zum einem die Box und ist die Information das dies ein Captcha feld ist überhaupt nötig wenn dies sowieso im Feld selbst steht?

**Comment by 12jr** [comment]
fixed in 12jr branch (removed the Schrifttext "Captcha" = label of the captcha form field => looks good)
