### ISSUE TITLE
Integration & Ableitung: Neue Spalten werden nicht in DB gespeichert.

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#123]
Wo das geschehen muss, ist schon im Code markiert (experiements/views.py).
DB-Spezialisten benötigt :)

**Comment by MOuli90** [comment]
@12jr Das ist doch hiermit erstmal nach hinten gestellt, bis sich der LBF dazu genauer äußert

**Comment by 12jr** [comment]
@MOuli90 Ja, die Issue ist noch von vor dem Treffen
