### ISSUE TITLE
Dashboard: Zu viele Projekte

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#125]
Auf dem Dashboard wird mir mein einziges Projekt fünf Mal angezeigt, auf `/projects/` korrekterweise nur ein Mal.

- Dashboard:
![grafik](https://user-images.githubusercontent.com/33256992/35461795-99b81fb8-02e9-11e8-8560-95000b201d53.png)
- `/projects/`:
![grafik](https://user-images.githubusercontent.com/33256992/35461812-aa706f7c-02e9-11e8-8211-da16c13b16c0.png)

**Comment by MOuli90** [comment]
@12jr Wie hast du das denn geschafft? Bei mir Lokal kann ich alles machen, das Projekt wird nur einmal angezeigt.
