### ISSUE TITLE
Farben der Plots mit Fraunhofer absprechen

### ISSUE THREAD

**Issue by Heggi95** [IT-PM-OpenAdaptronik/Webapp#148]

**Comment by Heggi95** [comment]
Erik Schwan, [01.02.18 16:55]
#e66101
#fdb863
#f7f7f7
#b2abd2
#5e3c99

Erik Schwan, [01.02.18 16:56]
#d7191c
#ffffbf
#abd9e9
#2c7bb6

**Comment by MOuli90** [comment]
@Heggi95 Hat es sich mit dem Merge Request erledigt?
