### ISSUE TITLE
Fokus auf Email bei Login-Formular und Registrieren-Formular

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#21]
- Beim Registrieren-Formular ist beim Aufruf der Seite das Email-Feld vorausgewählt, ist aber nicht das erste Feld --> username sollte autofocus haben
- Beim Login-Formular ist beim Aufruf der Seite das Email-Feld vorausgewählt

  - bei den puren Login-Pages (also auf /login/) ist das gut
  - aber auf der Startseite ("index") ist das ungünstig: Ruft man die Website auf einem Smartphone auf, wird automatisch zum Login-Formular heruntergescrollt.

**Comment by 12jr** [comment]
https://stackoverflow.com/questions/21515605/remove-autofocus-attribute-from-field-in-django
https://stackoverflow.com/a/20514357

**Comment by MOuli90** [comment]
Done
