### ISSUE TITLE
Login: 2. Fehlermeldung bei falschen Login-Daten weg

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#22]
1. Nicht Eingeloggt 
2. auf /login?next=/dashboard

**Comment by Heggi95** [comment]
Ihr Benutzername und Passwort stimmen nicht überein. Bitte versuche es erneut.
Bitte loggen Sie sich ein, um diese Seite zu sehen.

bei falschen logindaten

**Comment by 12jr** [comment]
fixed in 12jr-Branch
