### ISSUE TITLE
Startseite: Registrieren-Formular integrieren!

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#27]

**Comment by MOuli90** [comment]
@Maren4 Sollen wir das machen?

**Comment by Maren4** [comment]
Ich würde es so auf einer extra Seite lassen

**Comment by 12jr** [comment]
Dann designe ich die Startseite etwas um.
Oder wir lassen den User seine Email auf der Startseite zur Registrierung eingeben, sie wird per GET an die register-Page gesendet und dann mit python ausgelesen (also wie auf den ursprünglichen Mockups vorgesehen).

**Comment by 12jr** [comment]
s. vorigen Kommentar
