### ISSUE TITLE
Prozess Schritt 1: Hochladen

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#3]
Motivation: Als User möchte ich meine Daten zur weiteren Analyse hochladen und näher spezifizieren.

Funktion:
* alle Funktionen sind in der linken Spalte des Dashboards zu implementieren
* Daten als .csv, .xls, .xlsx hochladen
* eingeben, wie die Datei genau aufgebaut ist (welche Spalte was enthält)
* dem Datensatz Titel, Datum, Angaben zum Objekt (Kategorie, Modell, Typ, Kategorie-spezifische Angaben) hinzufügen
* dabei soll es auch möglich sein, eigene Kategorien, Modelle etc. und auch eigene Felder (wie bspw. Drehzahl) hinzuzufügen (evtl. nur Wunsch, nicht Muss).
* den Datensatz auf dem Server abspeichern oder nur temporär zur Analyse hochladen
* den Datensatz für alle sichtbar machen oder nur für mich (falls er dauerhaft hochgeladen wurde)
* KANN: Parameter für Analyse übergeben (nur im Experten-Modus)

Akzeptanzkriterium:
* es lassen sich die angegebenen File-Types hochladen
* von Fraunhofer vorgegebene Kategorien sind eingetragen
* alle unter Funktion beschriebenen Felder sind vorhanden, voll funktionsfähig (also bspw. beim Datumsfeld Auswahl über Kalender, Angaben zum Datei-Aufbau tauchen je nach File nach dem Upload auf etc.) und werden bei Eingabe korrekt in die DB eingetragen
* alle unter Funktion genannten Punkte sind implementiert

**Comment by MOuli90** [comment]
Wäre das Format XML nicht auch eine gute Wahl?

**Comment by 12jr** [comment]
Habe mich bei den Dateiformaten an denen orientiert, die bei dem Kickoff genannt wurden und - wenn ich mich richtig erinnere - die üblich sind. Aber xml ist vielleicht eine gute Idee für das Format, das wir intern wählen, um die Daten abzuspeichern, d.h. wir könnten die geuploadeten Files nach xml  konvertieren. On Nov 1, 2017 09:56, Alexander Kopp <notifications@github.com> wrote:Wäre das Format XML nicht auch eine gute Wahl?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




On Nov 1, 2017 09:56, Alexander Kopp <notifications@github.com> wrote:Wäre das Format XML nicht auch eine gute Wahl?
