### ISSUE TITLE
User Namen Redundanz nicht möglich

### ISSUE THREAD

**Issue by ErikBird** [IT-PM-OpenAdaptronik/Webapp#35]
Aktuell können sich keine User mit gleichem Namen registrieren. Bitte fixen

Ich weiß nicht wie man das Kommentar kommentiert, aber das ist mit Absicht, dass es jeden Usernamen nur einmal gibt, zum Filtern und so ist das einfacher :)

**Comment by MOuli90** [comment]
@Maren4 Unten ist ein Kommentarfeld. Diesen Issue schließe ich wieder. 

-> Der Username soll Unique sein.
