### ISSUE TITLE
Datum des Projekts visibility render

### ISSUE THREAD

**Issue by Heggi95** [IT-PM-OpenAdaptronik/Webapp#48]
Das Pop-Up Fenster zeigt trotzdem Text/Grafiken im Hintergrund. Diese versperren die Sicht auf ein Teil der Dati

**Comment by MOuli90** [comment]
@Heggi95 Bitte mehr Kommentieren. Ich verstehe es nicht 😄

**Comment by 12jr** [comment]
Die Datumsauswahl sieht nicht schön aus, weil sie die Überschrift einer darauffolgenden Karte nicht überdeckt. (z-index).

**Comment by 12jr** [comment]
![grafik](https://user-images.githubusercontent.com/33256992/34906350-258e6458-f86c-11e7-9b36-f28006b7d4cb.png)

**Comment by 12jr** [comment]
Ist nicht wirklich 100% gelöst, es kommt bei dem aktuellen Aufbau nur danach gerade kein Element im HTML vor, dass herüberragt... was aber reichen sollte.

**Comment by MOuli90** [comment]
@12jr Wenn es nochmal vorkommen sollte, dan machen wir ein neues Ticket :)
