### ISSUE TITLE
Datenauswahl punkte beschränken / infos einholen

### ISSUE THREAD

**Issue by ErikBird** [IT-PM-OpenAdaptronik/Webapp#55]
Die Datenauswahl mit den vom Admin eingestellten maximalen Datenpunkten verknüpfen

**Comment by MOuli90** [comment]
# TODO
Beschränkung aktuell fest im Code hinterlegt, dieser muss noch dynamisch aus der Datenbank ausgelesen werden.

**Comment by Heggi95** [comment]
dashboard\index.html  Zeile 11  Value durch Datenbankwert ersetzen
