### ISSUE TITLE
Profilbild löschen

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#68]
Man kann nur ein neues hochladen, es aber nicht löschen.

**Comment by TUmadao** [comment]
Der Admin kann löschen 
dem user stehen nur die Bilderupdate funktion zur verfügung
reicht das nicht ?

**Comment by 12jr** [comment]
Ich denke, der User sollte es auch löschen können

Sent with AquaMail for Android
http://www.aqua-mail.com

**Comment by MOuli90** [comment]
Ich werde es erstmal als "enhancement" eintragen.

**Comment by TUmadao** [comment]
wird hinzugefügt mit #101
