### ISSUE TITLE
Tooltip auf experiments/new/ bei grauem Button geht nicht mehr

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#82]
Wenn der Bereich zu groß ist - Zu viele Datenpunkte.

**Comment by 12jr** [comment]
https://github.com/IT-PM-OpenAdaptronik/Webapp/commit/23886b436b750ff40a9946f4b88a549cb73bb4da#diff-5b5f187104dfc04f4d22e56c52f81835R315
maybe wieder zurück zu diesem Stand

**Comment by Heggi95** [comment]
Funktioniert bei mir einwandfrei .

**Comment by 12jr** [comment]
Geht mysteriöserweise wieder (auch bei mir)
