### ISSUE TITLE
Fehlende Verlinkungen im Footer

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#84]
Im Footer sind immer noch nicht "Über" und "Lizenz" richtig Verlinkt. Über sollte auf die Openadaptronik Seite verweisen und die Lizenz verlinkt die Datei aus dem Github Repo.

**Comment by 12jr** [comment]
Lizenz ---> https://github.com/IT-PM-OpenAdaptronik/Webapp/blob/master/LICENSE

**Comment by TUmadao** [comment]
im pull request #101
