### ISSUE TITLE
Übersetzungen

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#86]
Alle Felder werden im Admin richtig übersetzt.

**Comment by TUmadao** [comment]
falls es noch andere stellen gibt die nicht übersetzt wurden 
hier rein schreiben

**Comment by TUmadao** [comment]
.../community/     Username am linken rand 
.../community/     project name beim anzeigen der Projekt

**Comment by TUmadao** [comment]
.../projetcs/detail/<projectsname>/<id>     projekt  zu projekt bearbeiten

**Comment by TUmadao** [comment]
Admin Measured übersetzen
admin max anzahl an datenpunkten anders übersetzen
