### ISSUE TITLE
Kalender mit Falschem Datumsformat

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#87]
Beim erstellen eines Experimentes, wird das Datum mit einem Falschen Datumsformat abgefragt. Siehe rattler/settings/base.py für das Richtige Datumsformat. 

Optimal wäre es wenn der Kalender automatisch das Datumsformat aus den Settings nimmt. (Evt. direkt oder über das i18n Modul)

**Comment by 12jr** [comment]
fixed in 12jr-Branch
