### ISSUE TITLE
Kategorien direkt in den Migrations Scripten

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#88]
Damit man die Hauptkategorien, die fest stehen, nicht jedes mal händisch eintragen muss, wäre es schön wenn diese in einem Migrationsscript hinterlegt werden. Damit werden diese Automatisch in die Datenbank eingetragen werden.

**Comment by MOuli90** [comment]
@Maren4 Kannst du hier die Liste der Hauptkategorien anheften?

**Comment by MOuli90** [comment]
@Maren4 Hier fehlen noch die Kategorien....

**Comment by Maren4** [comment]
·         Spielzeuge (Drohne, RC-Car, ...)
·         Fahrzeuge (PKW, LKW, Schiff, Flugzeug, …)
·         Hausgeräte (Waschmaschine, Toaster, Küchenmaschine, …)
·         Werkzeuge (Akkuschrauber, Bohrmaschine, Stichsäge, ….)
·         Maschinen (3D-Drucker, Drehbank, …)
·         IT-Geräte (Notebook, Tablet, Digitalkamera, …)
·         Gebäude (Wohnhaus, Brücke, Tiefgarage, …)
