### ISSUE TITLE
Texte entfernen

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#92]
Auf einigen Seiten werden immer noch Texte angezeigt, die da nicht hingehören. Bitte alle Templates durchgehen, diese Texte entfernen.

**Comment by Heggi95** [comment]
template und forms

**Comment by MOuli90** [comment]
+ Übersetzungen

**Comment by Heggi95** [comment]
Alle Templates forms und views , sind durchgegangen und die wichtigen Stellen mit TODO und dem dazugehörigen Wert ersetzt, dies bezieht sich aber hauptsächlich auf Experiment beschreibung und Datum.
