### ISSUE TITLE
Experimente speichern

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#93]
Ein neu Angelegtes Experiment sollte direkt in die Datenbank gespeichert werden. 

- Eine Experiment Detailseite muss angelegt werden (/projects/experiment/id) #59
- Alle weiteren Prozesse solten immer darunter liegen, Bsp. Tess: /projects/experiment/id/tess

**Comment by MOuli90** [comment]
#79

**Comment by 12jr** [comment]
> Eine Experiment Detailseite muss angelegt werden (/projects/experiment/id) 
Momentan `experiments/<id>`
