### ISSUE TITLE
Analyse - Standartwerte

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#94]
Die Standardwerte in den Analysen sollten bekannt sein und an den jeweiligen Inputs als Placeholder angezeigt werden (HTML Attribut "placeholder")

**Comment by Heggi95** [comment]
standartwerte sind jeweils Rang 4   Gausstd 2 bei mir lokal sind die Placeholder eingetragen jedoch wird die Frequenz dynamisch berechnet weshalb ein "placeholder" keinen sinn macht. Ich werde nochmals mit Erik reden und ansonsten meinen branch pushen
