### ISSUE TITLE
Analyse - FFT nicht richtig?

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#95]
Heute kam die frage auf, was bei der FFT Analyse angezeigt wird. Ich weiß nicht genau was angezeigt werden soll, aber es ist zu klären ob das was FFT hier macht auch richtig ist.

**Comment by MOuli90** [comment]
Nach Jörg wird aktuell nur der Realteil angezeigt. Vorschlag: Auswahl welcher Teil geplottet werden soll (Real, Imaginär, Absolut)

**Comment by Heggi95** [comment]
Hab die Methode jetzt umgeschrieben so das man mitübergeben kann ob real absolut oder imaginär teil mitgegeben wird. Wie schon erwähnt gibt es somit auch andere plots die dann erzeugt werden. Das einzige was im Moment nicht funktionieren will ist die Übergabe der Parameter per ajax ( selbes verfahren benutzt wie auch beim resampling)

**Comment by Heggi95** [comment]
funktioniert
