### ISSUE TITLE
Analyse - Speichern

### ISSUE THREAD

**Issue by MOuli90** [IT-PM-OpenAdaptronik/Webapp#96]
Als User möchte ich meine Analyse eines Experimentes als neues Experiment Speichern können.

Hier ist fraglich, ob es ein neues Experiment sein soll, oder ob man die "Filter Parameter" Speichert. Wichtig ist, das nach dem Speichern auf den Veränderten Daten weiter Analysiert werden können soll

**Comment by 12jr** [comment]
resolved in #185
