### ISSUE TITLE
Bei projects/detail/ wird auch bei fremden Projekten der Link "Neues Experiment" angezeigt

### ISSUE THREAD

**Issue by 12jr** [IT-PM-OpenAdaptronik/Webapp#99]
Bei projects/detail/ wird auch bei fremden Projekten der Link "Neues Experiment" angezeigt.

**Comment by MOuli90** [comment]
äquivalent zu dem Button Bearbeiten.

**Comment by 12jr** [comment]
fixed in 12jr branch
